name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH agent to deploy to DigitalOcean
      - name: Set up SSH agent for DigitalOcean
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_SSH_KEY }}

      # Create SSH Private Key on the Droplet and set correct permissions
      - name: Create SSH Private Key on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          echo '${{ secrets.ACTIONS_DEPLOY_SSH_KEY }}' > /root/.ssh/github_droplet_key &&
          chmod 600 /root/.ssh/github_droplet_key"

      # Add the SSH key to the agent on the Droplet
      - name: Add SSH Key to Agent on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
            eval \$(ssh-agent -s) &&
            ssh-add /root/.ssh/github_droplet_key &&
            ssh -T git@github.com || true"

      # Clone or Update Repository on Droplet
      - name: Clone or Update Repository on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          export GIT_SSH_COMMAND='ssh -i /root/.ssh/github_droplet_key -o StrictHostKeyChecking=no' &&
          if [ ! -d /root/Matplaner_backend ]; then
            git clone git@github.com:vindenez/Matplaner_backend.git /root/Matplaner_backend;
          else
            cd /root/Matplaner_backend && git pull origin main;
          fi"

      # Run Maven Build on the Droplet
      - name: Run Maven Build on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          cd /root/Matplaner_backend &&
          ./mvnw clean package -DskipTests"

      # List target directory on Droplet to verify the JAR file is present
      - name: List target directory contents on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          cd /root/Matplaner_backend/target && ls -al"

      # Build the Docker image on the Droplet
      - name: Build Docker image on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          cd /root/Matplaner_backend &&
          docker build -t matplaner-backend ."

      # Create or Update .env file on the Droplet to store environment variables
      - name: Create or Update .env file on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          echo 'SUPABASE_URL=${{ secrets.SUPABASE_URL }}' > /root/.env &&
          echo 'SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}' >> /root/.env &&
          echo 'SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}' >> /root/.env &&
          echo 'SUPABASE_BUCKET=${{ secrets.SUPABASE_BUCKET }}' >> /root/.env &&
          echo 'REDIS_HOST=${{ secrets.REDIS_HOST }}' >> /root/.env &&
          echo 'REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}' >> /root/.env &&
          echo 'REDIS_PORT=${{ secrets.REDIS_PORT }}' >> /root/.env &&
          echo 'REDIS_URL=${{ secrets.REDIS_URL }}' >> /root/.env &&
          echo 'DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}' >> /root/.env &&
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> /root/.env &&
          echo 'DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}' >> /root/.env"

      # Deploy the Docker image using Docker Compose on the Droplet
      - name: Deploy the Docker image using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.210.156 "
          docker-compose -f /root/docker-compose.yml up -d"
